# Generated by Django 2.2.1 on 2019-09-15 20:28

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cpf',
            field=models.CharField(max_length=14),
            preserve_default=False,
        ),
    ]
