# Generated by Django 2.2.1 on 2019-09-15 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190915_1733'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='cpf',
        ),
    ]
