# Generated by Django 2.2.1 on 2019-09-15 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_profile_cpf'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cpf',
            field=models.CharField(default='87010137005', max_length=14),
            preserve_default=False,
        ),
    ]
