# Generated by Django 2.2.1 on 2019-09-15 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_profile_cpf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='cpf',
        ),
    ]
