# Generated by Django 2.2.1 on 2019-09-15 23:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_profile_cpf'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cpf',
            field=models.CharField(default='39604497049', max_length=14),
        ),
        migrations.AddField(
            model_name='profile',
            name='data_nascimento',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
