# Generated by Django 2.2.1 on 2019-11-03 04:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20191101_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='data_nascimento',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
