# Generated by Django 2.2.7 on 2019-11-14 00:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20191113_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='data_nascimento',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
