# Generated by Django 2.2.1 on 2019-09-06 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storage',
            old_name='content',
            new_name='descricao',
        ),
    ]
