# Generated by Django 2.2.1 on 2019-09-07 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_auto_20190905_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='storage',
            name='quantidade',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
