# Generated by Django 2.2.1 on 2019-11-02 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0003_storage_quantidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='storage',
            name='ativo',
            field=models.CharField(choices=[('A', 'Ativo'), ('I', 'Inativo')], default=1, max_length=1),
            preserve_default=False,
        ),
    ]
