# Generated by Django 2.2.7 on 2019-11-28 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vax', '0002_auto_20190905_2147'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vax',
            old_name='temperature',
            new_name='temperatura',
        ),
    ]
