# Generated by Django 2.2.1 on 2019-09-08 22:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('storage', '0003_storage_quantidade'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vax', '0002_auto_20190905_2147'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='storage.Storage')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='usuario', to=settings.AUTH_USER_MODEL)),
                ('vacina', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='vax.Vax')),
            ],
        ),
    ]
