# Generated by Django 2.2.1 on 2019-09-06 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='station',
            old_name='descrytion',
            new_name='descricao',
        ),
        migrations.RenameField(
            model_name='station',
            old_name='name',
            new_name='nome',
        ),
    ]
